version: 2
updates:
- package-ecosystem: nuget
  directory: "/Aleph1.Logging"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: PostSharp
    versions:
    - 6.8.10
    - 6.8.8
    - 6.8.9
    - 6.9.3
  - dependency-name: NLog
    versions:
    - 4.7.7
    - 4.7.8
